In [5]:
import numpy as np
import math
from coursework_functions import print_2d_array, perform_convolution

In [6]:
template = [
    [15, 14, 13, 12, 11],
    [10, 9, 8, 7, 6],
    [5, 4, 3, 2, 1]
]

numpy_template = np.array(template)

print(numpy_template)

[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [9]:
def invert_template(original_template: np.ndarray):
    inverted_template = original_template.copy()
    inverted_template.reverse()

    for row in template:
        row.reverse()

    return inverted_template

#inverted_template = invert_template(numpy_template)
invert_template = np.flip(invert_template)

inverted_template

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]