In [209]:
import numpy as np
from coursework_functions import print_2d_array
from tqdm import tqdm

In [210]:
input_image = [
    [1, 1, 1, 0, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 1, 1, 1],
    [0, 0, 1, 1, 0],
    [0, 1, 1, 0, 0]
]

In [211]:
example_kernel = [
    [1, 0, 1],
    [0, 1, 0],
    [1, 0, 1]
]

In [212]:
def perform_numpy_convolution(image: np.ndarray, template: np.ndarray):
    # Flip the template around both axes
    inverted_template = np.flip(template)

    x, y = len(image), len(image[0])
    offset = int((len(template) - 1) / 2)

    padded_image = np.pad(image, [offset, offset], 'constant', constant_values=[0, 0])

    out = np.zeros((x, y))
    print(range(0+offset, x))
    print(range(0+offset, y))
    for row in tqdm(range(0+offset, x+1)):
        for column in range(0+offset, y+1):
            section = np.array(padded_image[row-offset:row+offset+1,column-offset:column+offset+1])
            print(section)
            out[row-1][column-1] = np.sum(np.multiply(section, inverted_template))

    return out

In [213]:
numpy_image = np.array(input_image)
numpy_template = np.array(example_kernel)

In [214]:
output_image = perform_numpy_convolution(numpy_image, numpy_template)

range(1, 5)
range(1, 5)


100%|██████████| 5/5 [00:00<00:00, 610.83it/s]

[[0 0 0]
 [0 1 1]
 [0 0 1]]
[[0 0 0]
 [1 1 1]
 [0 1 1]]
[[0 0 0]
 [1 1 0]
 [1 1 1]]
[[0 0 0]
 [1 0 0]
 [1 1 0]]
[[0 0 0]
 [0 0 0]
 [1 0 0]]
[[0 1 1]
 [0 0 1]
 [0 0 0]]
[[1 1 1]
 [0 1 1]
 [0 0 1]]
[[1 1 0]
 [1 1 1]
 [0 1 1]]
[[1 0 0]
 [1 1 0]
 [1 1 1]]
[[0 0 0]
 [1 0 0]
 [1 1 0]]
[[0 0 1]
 [0 0 0]
 [0 0 0]]
[[0 1 1]
 [0 0 1]
 [0 0 1]]
[[1 1 1]
 [0 1 1]
 [0 1 1]]
[[1 1 0]
 [1 1 1]
 [1 1 0]]
[[1 0 0]
 [1 1 0]
 [1 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 1]]
[[0 0 1]
 [0 0 1]
 [0 1 1]]
[[0 1 1]
 [0 1 1]
 [1 1 0]]
[[1 1 1]
 [1 1 0]
 [1 0 0]]
[[1 1 0]
 [1 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 1]
 [0 0 0]]
[[0 0 1]
 [0 1 1]
 [0 0 0]]
[[0 1 1]
 [1 1 0]
 [0 0 0]]
[[1 1 0]
 [1 0 0]
 [0 0 0]]
[[1 0 0]
 [0 0 0]
 [0 0 0]]


In [215]:
print_2d_array(output_image, decimal_places=0)

2 2 3 1 1 
1 4 3 4 1 
1 2 4 3 3 
1 2 3 4 1 
0 2 2 1 1 
